---

- name: restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu'


- name: restart crio
  service:
    name: crio
    daemon_reload: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu'

- name: restart haproxy
  service:
    name: haproxy
    daemon_reload: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu'


- name: reload haproxy
  service:
    name: haproxy
    state: reloaded
  when: ansible_distribution == 'Ubuntu'

- name: reload sysctl
  command: "sysctl --system"

- name: reload iptables
  command: "iptables-restore --noflush /etc/iptables/rules.v4"

- name: reboot node
  reboot:
    reboot_timeout: 3600
