---


- name: restart networking
  service:
    name: networking
    state: restarted
  async: 120
  poll: 0
  register: network_restarting

- name: wait for networking restart
  async_status:
    jid: "{{ network_restarting.ansible_job_id }}"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30
  listen: restart networking

- name: update initramfs
  command: "update-initramfs -u"
  when: ansible_distribution == 'Ubuntu'